### PR TITLE
CSRs fixes and improvements

### PR DESCRIPTION
**Pull request by arsv**
The changes replace common csr[] array with named fields in CPURISCVState, and remove privileged CSRs from user-only builds.

### CODE REVIEW

**Comment by sagark** [comment]
I'm getting failures on the rv64mi-p-breakpoint and rv32mi-p-breakpoint tests on this.

**Comment by arsv** [comment]
Only those two tests?

I'm unable to run any tests from riscv/riscv-tests, both pre- and post this patches, and I'm unable to re-build the tests with current toolchain. Trying to figure out why.

This is so wrong.

**Comment by sagark** [comment]
Yes, only those two. Are you building everything from https://github.com/riscv/riscv-tools/releases/tag/priv-1.9-rc0 ?

**Comment by arsv** [comment]
Nope, riscv-gnu-toolchain current master and riscv-tests current master.

Checked out priv-1.9 in riscv-tests, everything builds well now. Moving on to qemu issues.

**Comment by sagark** [comment]
Okay, make sure you use the linked release and not the priv-1.9 branches of things. The priv-1.9 branches have moved on to contain WIP stuff for the next 1.9.x spec.

**Comment by arsv** [comment]
Ok, fixed I think. TDRSELECT was defined for reading (as a hard-wired 0) but not for writing, resulting in illegal insn exception. The test apparently expects that even if not implemented, this CSR should safely read/write as 0.

Side note, even with perfectly matched toolchain and tests tags, I can only run 64-bit tests now.
For any 32-bit tests, qemu hangs. Probably this issue: https://github.com/riscv/riscv-qemu/issues/23#issuecomment-249579907
Building the tests with priv-1.9 toolchain results in both 32- and 64-bit tests hanging.

Happens the same way with and without these patches, so probably unrelated.
Did not investigate this further yet.

**Comment by sagark** [comment]
Hmm, I'm not able to reproduce the hangs when using a cleanly built copy of the priv-1.9-rc0 release of riscv-tools. What's your build environment like?

In any case, everything passes for me now, so I'm merging this.

**Comment by arsv** [comment]
The build environment is a regular x86_64 linux system, glibc-2.24, gcc-6.2.1 and riscv-tools tag priv-1.9-rc0 built by running build.sh.

Ran it again. Tests before rv32ui-p-addi and  after rv32um-v-div pass, those two and apparently everything in-between hangs. The tests that hang keep writing 0x1800 to CSR 0x300 (mstatus) — that's with CSR debug enabled.

**Pull request merged**
