### PR TITLE
RVC decoding

### PR DESCRIPTION
**Pull request by bkoppelmann**
Hi Sagar,

it has been some time :). However I managed to implement RVC for QEMU which passes all the tests of riscv-test. I wasn't able to run torture on it but here it is for now.

### CODE REVIEW

**Comment by kito-cheng** [comment]
Awesome! I can help to run it with gcc testsuite!

**Comment by brucehoult** [comment]
Build and checked on my favourite Fibonacci toy benchmark with -march=rv64gc. Looks good! Thanks!

0000000000010214 <fib>:
   10214:       4785                    li      a5,1
   10216:       02a7d463                ble     a0,a5,1023e <fib+0x2a>
   1021a:       1101                    addi    sp,sp,-32
   1021c:       ec06                    sd      ra,24(sp)
   1021e:       e822                    sd      s0,16(sp)
   10220:       e426                    sd      s1,8(sp)
   10222:       842a                    mv      s0,a0
   10224:       3579                    addiw   a0,a0,-2
   10226:       fefff0ef                jal     ra,10214 <fib>
   1022a:       84aa                    mv      s1,a0
   1022c:       fff4051b                addiw   a0,s0,-1
   10230:       fe5ff0ef                jal     ra,10214 <fib>
   10234:       9d25                    addw    a0,a0,s1
   10236:       60e2                    ld      ra,24(sp)
   10238:       6442                    ld      s0,16(sp)
   1023a:       64a2                    ld      s1,8(sp)
   1023c:       6105                    addi    sp,sp,32
   1023e:       8082                    ret

0000000000010240 <main>:
   10240:       1141                    addi    sp,sp,-16
   10242:       e406                    sd      ra,8(sp)
   10244:       6588                    ld      a0,8(a1)
   10246:       032000ef                jal     ra,10278 <atoi>
   1024a:       fcbff0ef                jal     ra,10214 <fib>
   1024e:       85aa                    mv      a1,a0
   10250:       0001a537                lui     a0,0x1a
   10254:       a0850513                addi    a0,a0,-1528 # 19a08 <__trunctfdf2+0x454>
   10258:       2b4000ef                jal     ra,1050c <printf>
   1025c:       4501                    li      a0,0
   1025e:       60a2                    ld      ra,8(sp)
   10260:       0141                    addi    sp,sp,16
   10262:       8082                    ret

**Comment by kito-cheng** [comment]
rv32imac's Hello world with static linked can't run correctly.

here is the binary: 
https://www.dropbox.com/s/zqtace7gnwgl8no/hello.rv32imac?dl=0

```
$ qemu-riscv32  hello.rv32imac 
Illegal instruction (core dumped)
```

**Comment by bkoppelmann** [comment]
Hmm I can't even run your binary on spike..

spike --isa=RV32IMAC -l hello.rv32imac 
terminate called after throwing an instance of 'trap_load_access_fault'

**Comment by brucehoult** [comment]
Actually, it seems not to be working always with rv32c. rv64c is fine, even with the 

This works on qemu now in rv32gc (as well as rv32g, rv64g, rv64gc)

            .equ STDOUT,    1
    	.equ SYSCALL_WRITE,     64
    	.equ SYSCALL_EXIT,      93
    
    	.globl _start
    _start:
    	li	a0, STDOUT
    1:	auipc	a1, %pcrel_hi(str)
    	addi	a1, a1, %pcrel_lo(1b)
    	li	a2, 14
    	li	a7, SYSCALL_WRITE
    	ecall
    	li	a7, SYSCALL_EXIT
    	ecall
    
    str:	.ascii	"Hello Risc-V!\n"

But this doesn't work on qemu if compiled for rv32gc (even with newlib compiled without rvc):

    #include <stdio.h>
    
    int main(){
      printf("hello world!\n");
      return 0;
    }

    00010164 <main>:
       10164:       1141                    addi    sp,sp,-16
       10166:       c606                    sw      ra,12(sp)
       10168:       00013537                lui     a0,0x13
       1016c:       49850513                addi    a0,a0,1176 # 13498 <__errno+0x8>
       10170:       2411                    jal     10374 <puts>
       10172:       4501                    li      a0,0
       10174:       40b2                    lw      ra,12(sp)
       10176:       0141                    addi    sp,sp,16
       10178:       8082                    ret

It's fine however in qemu with rv64gc:

    0000000000010214 <main>:
       10214:       1141                    addi    sp,sp,-16
       10216:       e406                    sd      ra,8(sp)
       10218:       00014537                lui     a0,0x14
       1021c:       99850513                addi    a0,a0,-1640 # 13998 <__errno+0x8>
       10220:       2f0000ef                jal     ra,10510 <puts>
       10224:       4501                    li      a0,0
       10226:       60a2                    ld      ra,8(sp)
       10228:       0141                    addi    sp,sp,16
       1022a:       8082                    ret

The only differences seem to be sd/ld vs sw/lw and the compressed jal in 32 bit.

**Comment by brucehoult** [comment]
It's definitely the compressed jal. This works with "riscv32-unknown-elf-as -march=rv32gc" (or with "riscv32-unknown-elf-gcc -march=RV32IC -nostdlib"):

            .equ STDOUT,    1
            .equ SYSCALL_WRITE, 64
            .equ SYSCALL_EXIT,  93
    
            .globl _start
    _start:
            #jal    sub
            .byte   0xef, 0x00, 0x00, 0x02
    
            li      a0, STDOUT
    1:      auipc   a1, %pcrel_hi(str)
            addi    a1, a1, %pcrel_lo(1b)
            li      a2, 14
            li      a7, SYSCALL_WRITE
            ecall
            li      a7, SYSCALL_EXIT
            ecall
    
    sub:    ret
            
    str:    .ascii "Hello Risc-V!\n"

But if you uncomment the "jal sub" to get a compressed one and comment out the .byte definition of a 32-bit jal then it doesn't work.

(Is there a better way to force the assembler to make a 32 bit opcode when compresses opcodes are enabled?)

**Comment by brucehoult** [comment]
Fixed it for you :-)

    diff --git a/target-riscv/translate.c b/target-riscv/translate.c
    index 29e267b..09376d0 100644
    --- a/target-riscv/translate.c
    +++ b/target-riscv/translate.c
    @@ -1527,7 +1527,7 @@ static void decode_RV32_64C1(CPURISCVState *env, DisasContext *ctx)
                           GET_C_IMM(ctx->opcode));
     #else
             /* C.JAL(RV32) -> jal x1, offset[11:1] */
    -        gen_jal(env, ctx, 1, GET_C_IMM(ctx->opcode));
    +        gen_jal(env, ctx, 1, GET_C_J_IMM(ctx->opcode));
     #endif
             break;
         case 2:

**Comment by brucehoult** [comment]
Now it works even if I compile the whole of newlib with rv32gc, which drops stripped helloWorld from 22752 bytes to 18560 byes, a 1.226 ratio, or 4192 byte and 18.4% saving.

My Fibonacci benchmark goes from 54972 to 41724, saving 13248 bytes or 24.10 percent.

    #include <stdio.h>
    #include <stdlib.h>
    
    int fib(int n){
      return n<2 ? n : fib(n-2) + fib(n-1);
    }
    
    int main(int argc, char **argv){
      if (argc < 2){
        printf("Usage: %s <integer>\n", argv[0]);
        return 1;
      }
      printf("%d\n", fib(atoi(argv[1])));
      return 0;
    }

**Comment by brucehoult** [comment]
Also fixes @kito-cheng's binary.

**Comment by bkoppelmann** [comment]
I've merged the patch. Thanks to both of you for testing.

**Comment by kito-cheng** [comment]
RV32IMAC and RV64IMAC is passed GCC testsuite but RV32GC and RV64GC not, it's got ~1000 fails, I will put test case later.

**Comment by aswaterman** [comment]
@kito-cheng it could be a binutils bug too :) thanks for looking into it.

**Comment by kito-cheng** [comment]
@aswaterman We have test rv32imac, rv64imac, rv32gc and rv64gc for elf/newlib toolchain with our internal simulator is pass all gcc testsuite except very few reasonable fail (~2 fail), so it's cause by qemu is more possible.

**Comment by bkoppelmann** [comment]
Hi kito-cheng,

how can I run these tests you mentioned? Are they part of dejagnu?

**Comment by kito-cheng** [comment]
Use riscv-gnu-toolchain:
```
$ ./riscv-gnu-toolchain/configure --prefix=/home/kito/riscv-workspace/rv32imafdc --with-arch=rv32imafdc  --disable-multilib
$ make linux  -j`nproc`
$ make check-gcc-linux -j`nproc`
```

**Comment by aswaterman** [comment]
So @bkoppelmann is this ready for merging?

**Comment by bkoppelmann** [comment]
Hmm, I don't think so. I'm still tickering around with gcc's testsuit as well as csmith by @cliffordwolf.

**Comment by aswaterman** [comment]
Cool, keep us posted!

**Comment by bkoppelmann** [comment]
Hey @kito-cheng, I think I fixed the problem. Can you confirm it by run the gcc testsuit again?

**Comment by aswaterman** [comment]
I ran it last night and saw about 500 failures, down from 1000.  So I think you fixed _a_ bug.

Here's an example of a test that still fails in qemu, but passes on Spike: https://github.com/riscv/riscv-gcc/blob/riscv-gcc-6.1.0/gcc/testsuite/gcc.dg/torture/pr55555.c

**Comment by brucehoult** [comment]
@aswaterman hmm, 32G and 64G work. 32GC and 64GC both give all results 0.0 with -O0, fail with -O1 or -Os, segfaults qemu with -O2 or -O3

Seems to be more than one problem here.

**Comment by brucehoult** [comment]
@aswaterman @bkoppelmann Fixed in PR https://github.com/bkoppelmann/riscv-qemu/pull/2

**Comment by aswaterman** [comment]
I think that fixes RV64.  Looking into RV32.

**Comment by kito-cheng** [comment]
Last decode bug for RV32G:
https://github.com/kito-cheng/riscv-qemu/commit/4f1811c774d0ac494659ca1657a6db63a50a65a8

**Comment by bkoppelmann** [comment]
Thanks to all of you for testing and fixing these bugs. I will clean the PR up and resubmit and I guess then it's ready for merging.

**Pull request closed without merging**
