### PR TITLE
PMP bug fixes

### PR DESCRIPTION
**Pull request by dayeol**
Split  a commit of #150 into two.

### CODE REVIEW

**Comment by dayeol** [comment]
@alistair23 I've split the original PR into two commits.
Also submitted the same patches to qemu-devel via email.
Please let me know if I'm doing something wrong; I'm first to submit a patch to qemu :D

**Comment by alistair23** [comment]
Thanks for that @dayeol . I saw your two patch emails, they haven't yet propagate to the QEMU list, but for your first patch I think that just takes time.

**Comment by dayeol** [comment]
Thanks a lot!

**Comment by michaeljclark** [comment]
I've merged these into the `qemu-for-upstream` branch from your `pmp-napot-fix` branch, so closing this PR. Thanks!

**Pull request closed without merging**
