### PR TITLE
linux-user code, and minor improvements

### PR DESCRIPTION
**Pull request by arsv**

### CODE REVIEW

**Comment by sagark** [comment]
Looks good to me, thanks.

**Comment by sorear** [comment]
@sagark @arsv So I've tested this by injecting it into [the Fedora Docker image](https://hub.docker.com/r/sorear/fedora-riscv-wip/), and it seems to work.  I'm currently using arsv/riscv-qemu@e220f23 in the image; should I switch to the RISC-V organization QEMU?  What would be the pros and cons?

**Comment by sagark** [comment]
If things are working, I would go ahead and switch. We added linux-user here so that we don't have to maintain duplicate codebases for the shared translation code between system-mode and linux-user mode. This repo reflects the codebase that we're working on upstreaming (see https://lists.gnu.org/archive/html/qemu-devel/2016-09/msg06635.html). We'll incorporate improvements suggested by upstream here.

**Comment by sorear** [comment]
@sagark Working, but with at least one regression; the following test program runs to completion previously, but now enters a SIGSEGV loop and has to be `kill -9`ed:

```
#include <signal.h>
#include <setjmp.h>
#include <unistd.h>
#include <stdio.h>

jmp_buf jb;
void sighand(int signo) {
        write(2,"SEGV caught\n",12);
        signal(SIGSEGV, SIG_DFL);
        longjmp(jb,1);
}

int main() {
        if (setjmp(jb)) {
                puts("Longjmp from segv handler\n");
                return 0;
        }
        signal(SIGSEGV, sighand);
        asm("li t0, 0; ld t0, 0(t0)");
        return 1;
}
```

(this came up during a rpmbuild --rebuild of gforth, which turned up three separate bugs in arsv/riscv-qemu on Saturday so I thought it'd be a good stress test of the reconverged qemu)

**Comment by sagark** [comment]
The fix in 0fcb37124ba4bf6a341c7ec1dbbc8f89d3d24d68 allows the program to complete on my end.

**Comment by sorear** [comment]
testing

**Comment by sorear** [comment]
@sagark Passes the gforth-0.7.3-3.fc24.src.rpm test with that commit.  Would it make sense to mention the filesystem image in the README (link in my first comment) as an alternative to building the cross-compiler yourself?

**Comment by sagark** [comment]
Great. Yeah that would be useful. I added a blurb to the README.

**Pull request merged**
