### PR TITLE
implement target disassembler and integrate riscv-tests into qemu test

### PR DESCRIPTION
**Pull request by cmchao**
disassembler
    follow other architecture to use binutils to implement target disassembler 

tests
   integrate riscv-tests to make refactoring more comfortable

### CODE REVIEW

**Comment by kito-cheng** [comment]
@sorear  @sagark  ping

**Comment by aswaterman** [comment]
I'm not sure we want to import the riscv-tests into riscv-qemu, since they will get out of sync?

**Comment by sorear** [comment]
Generally speaking I'd rather not import anything into this repository unless it's supposed to go out in @sagark's next qemu-devel patchset.  I doubt upstream would like a copy of riscv-tests (although, looking at tests/tcg/lm32/, it might make sense to ask qemu-devel).

We should at least provide documentation on how to run it against riscv-tests, though.

**Comment by cmchao** [comment]
The original thought is to make refactor comfortable since I am not familiar with risc-v architecture.  There may be several choices.
1. apply my patch.  I choose this implementation since other architectures, cris and lm32  have similar test framework in the tests/tcg/.  Even ARM/MIPS also have small helloworld tests which are not included in "make test" flow. 
2. use the https://github.com/arsv/riscv-qemu-tests/  created by Alex Suykov to test linux-user mode.
3. modify riscv-tests to make it work with Qemu.
I just want a suite of unit tests

Besides, a curious question, what is the current status of upstream merging ?

**Comment by sagark** [comment]
Ideally we can hook riscv-tests into qemu's tests by submoduling riscv-tests (for system mode) and arsv/riscv-qemu-tests for user mode, I don't think that they should be committed to this repo. However, automating the tests (and plugging them into travis) is a good idea for handling PRs here. I'll take a look at the PR after some deadlines next week. 

If you just need to run tests, arsv/riscv-qemu-tests should run for user mode and the included hacking_files/run-rv-tests.py script should run the standard riscv-tests for system mode.

There's still some cleanup that has to be done based on the last set of upstream feedback, which I haven't had time to do.

**Comment by sagark** [comment]
Can you make a new PR just for the disas components for now?

For the testing side of things, I think we can stick with the scripts that exist for now, perhaps with better documentation in the readme (although it already points to both of the ways I outlined above).

**Comment by cmchao** [comment]
I have removed the unittest part and send another pull, #51 
Thanks

**Pull request closed without merging**
