### PR TITLE
fix matching logic of pmp_hart_has_privs

### PR DESCRIPTION
**Pull request by wxjstz**
Should skip the empty PMP entry.

### CODE REVIEW

**Comment by michaeljclark** [comment]
Can you please re-target your PR to the new `qemu-for-testing` branch (i just made)?

I'll merge them there and integrate `qemu-for-upstream` and `qemu-for-testing` into riscv-all.

Alternatively if you have a test case I can try locally I can merge them straight to `qemu-for-upstream` (which has had extensive testing, just not yet for PMP).

Thanks very much indeed.

**Comment by michaeljclark** [comment]
You could also fold your series into one PR i.e. one inbound/outbound pull at a time. You don't need to do that but its less PRs to retarget. I can add your tree as a local remote and do this locally if I get to it first. thx

**Comment by michaeljclark** [comment]
I can't retarget PRs, so I added you as a remote and integrated locally.

Your changes are here: https://github.com/riscv/riscv-qemu/commits/qemu-for-testing

Closing this PR. If you target `qemu-for-testing` they can be merged easily, and i'll work on making them appear in `riscv-all`. Thanks!

**Comment by wxjstz** [comment]
I try to test my pmp code base on riscv-qemu/riscv-probe.
This is the problem I found and the test passed.

However, riscv-qemu's pmp still has the error I want to solve.

**Pull request closed without merging**
