### PR TITLE
riscv: Fix build warning on 32 bit environment (#44)

### PR DESCRIPTION
**Pull request by kito-cheng**

### CODE REVIEW

**Comment by sorear** [comment]
This is still not quite working for me.

```
test@3fb75db9de38:~/riscv-qemu$ make -k
  CC    riscv32-softmmu/target-riscv/translate.o
/home/test/riscv-qemu/target-riscv/translate.c: In function 'riscv_cpu_dump_state':
/home/test/riscv-qemu/target-riscv/translate.c:1541:9: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t' [-Werror=format=]
         cpu_fprintf(f, " %s %016lx", fpr_regnames[i], env->fpr[i]);
         ^
cc1: all warnings being treated as errors
/home/test/riscv-qemu/rules.mak:60: recipe for target 'target-riscv/translate.o' failed
make[1]: *** [target-riscv/translate.o] Error 1
  CC    riscv32-softmmu/target-riscv/helper.o
/home/test/riscv-qemu/target-riscv/helper.c: In function 'riscv_cpu_unassigned_access':
/home/test/riscv-qemu/target-riscv/helper.c:278:5: error: format '%lX' expects argument of type 'long unsigned int', but argument 2 has type 'hwaddr' [-Werror=format=]
     printf("unassigned Address: %016lX\n", addr);
     ^
/home/test/riscv-qemu/target-riscv/helper.c: In function 'riscv_cpu_do_interrupt':
/home/test/riscv-qemu/target-riscv/helper.c:388:9: error: left shift count >= width of type [-Werror]
         fixed_cause |= (1L << 63);
         ^
cc1: all warnings being treated as errors
/home/test/riscv-qemu/rules.mak:60: recipe for target 'target-riscv/helper.o' failed
make[1]: *** [target-riscv/helper.o] Error 1
make[1]: Target 'all' not remade because of errors.
Makefile:205: recipe for target 'subdir-riscv32-softmmu' failed
make: *** [subdir-riscv32-softmmu] Error 2
make: Target 'all' not remade because of errors.
```

**Comment by kito-cheng** [comment]
I leave this one since I don't know how to fix correctly.
```
/home/test/riscv-qemu/target-riscv/helper.c: In function 'riscv_cpu_do_interrupt':
/home/test/riscv-qemu/target-riscv/helper.c:388:9: error: left shift count >= width of type [-Werror]
         fixed_cause |= (1L << 63);
         ^
```

**Comment by sorear** [comment]
That needs to depend on the number of bits in fixed_cause… let me try to fix it

**Comment by sorear** [comment]
@kito-cheng ok, it needs to be (TARGET_LONG_BITS - 1).  I suspect there are other width issues in here, gonna test some more before posting the patch

**Comment by sorear** [comment]
@sagark When do we want to move QEMU to 1.9.1?  My last attempt fell over because of the mucounteren encoding thing.

**Comment by sorear** [comment]
```
diff --git a/target-riscv/helper.c b/target-riscv/helper.c
index 97b5244..28183de 100644
--- a/target-riscv/helper.c
+++ b/target-riscv/helper.c
@@ -385,7 +385,7 @@ void riscv_cpu_do_interrupt(CPUState *cs)
         /* hacky for now. the MSB (bit 63) indicates interrupt but cs->exception
            index is only 32 bits wide */
         fixed_cause = cs->exception_index & 0x0FFFFFFF;
-        fixed_cause |= (1L << 63);
+        fixed_cause |= (1L << (TARGET_LONG_BITS - 1));
     } else {
         /* fixup User ECALL -> correct priv ECALL */
         if (cs->exception_index == RISCV_EXCP_U_ECALL) {
@@ -425,7 +425,7 @@ void riscv_cpu_do_interrupt(CPUState *cs)
         deleg = env->mideleg, bit &= ~(1L << (TARGET_LONG_BITS - 1));
     }
 
-    if (env->priv <= PRV_S && bit < 64 && ((deleg >> bit) & 1)) {
+    if (env->priv <= PRV_S && bit < TARGET_LONG_BITS && ((deleg >> bit) & 1)) {
         /* handle the trap in S-mode */
         /* No need to check STVEC for misaligned - lower 2 bits cannot be set */
         env->pc = env->stvec;
```

With this it can boot bbl, although getting a bbl that will actually work is a wee bit involved ( https://github.com/riscv/riscv-pk/issues/43#issuecomment-267533629 ).  Haven't tested Linux.  The config string hard-codes rv64imafd; good thing nobody is looking at that part yet.

**Comment by sagark** [comment]
There's a branch [here](https://github.com/riscv/riscv-qemu/tree/priv-1.9.1
) that should support v1.9.1, but I haven't merged it yet since I haven't had a chance to extensively test (probably next week), but it boots linux at least.

Sidenote, one thing that's on the TODO list/would be nice to have is to make the .travis.yml test more things so we can develop more rapidly and so that it's easier to one-click merge PRs. Not sure how much work it would take, but building https://hub.docker.com/r/sorear/fedora-riscv-wip/ automatically and checking for regressions would be a useful test.

**Pull request merged**
